name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout - stáhne kód do CI prostředí
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Nastavení Node verze
      - name: Use Node.js 20
        uses: actions/setup-node@v4

      # 3) Instalace závislostí
      - name: Install dependencies
        run: npm install

      # 4) Build projektu
      - name: Build
        run: npm run build

      # 5) Nastavení GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 6) Výsledek uploadneme
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Cesta, kde se po buildu vytvoří výsledný projekt 
          path: ./dist
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
